### PR TITLE
Add copyright and license information

### PR DESCRIPTION
**Pull request by johanvx**
SVG files are still not covered.

### CODE REVIEW

**Comment by Ginakira** [comment]
Nice job.
By the way, can you write a script to create/update license information in files? Or use existing tools to do this.

**Review by Ginakira — APPROVED** [review]

**Comment by johanvx** [comment]
> Nice job. By the way, can you write a script to create/update license information in files? Or use existing tools to do this.

Oh, I forgot to mention. So, there are [some existing tools](https://spdx.dev/tools-community/), and I personally choose to use [fsfe/reuse-tool](https://github.com/fsfe/reuse-tool). It's written in Python and can be installed by `pipx install reuse` (my preferred way). You can also use `pip` or `conda` to install it, or run it directly with `pipx run reuse ...`.

What I've done is:

```bash
reuse annotate --license "GPL-3.0-or-later" \
               --copyright-style string-c \
               --year "2022-2023" \
               --copyright "PMR Fansub" \
               src/components/* src/config/* ... # specify files to annotate
```

**Comment by johanvx** [comment]
And under which license(s) the SVG files are provided? Those files contain some icon(s) from other project(s). We shall check the corresponding license(s).

**Comment by Ginakira** [comment]
> And under which license(s) the SVG files are provided? Those files contain some icon(s) from other project(s). We shall check the corresponding license(s).

Please check this if it's convenient for you.
If these icons are not licensed, make them consistent with the project's license.

**Comment by Ginakira** [comment]
> > Nice job. By the way, can you write a script to create/update license information in files? Or use existing tools to do this.
> 
> 
> 
> Oh, I forgot to mention. So, there are [some existing tools](https://spdx.dev/tools-community/), and I personally choose to use [fsfe/reuse-tool](https://github.com/fsfe/reuse-tool). It's written in Python and can be installed by `pipx install reuse` (my preferred way). You can also use `pip` or `conda` to install it, or run it directly with `pipx run reuse ...`.
> 
> 
> 
> What I've done is:
> 
> 
> 
> ```bash
> 
> reuse annotate --license "GPL-3.0-or-later" \
> 
>                --copyright-style string-c \
> 
>                --year "2022-2023" \
> 
>                --copyright "PMR Fansub" \
> 
>                src/components/* src/config/* ... # specify files to annotate
> 
> ```
> 
> 

Consider adding the instructions to the document.

**Comment by johanvx** [comment]
> > > Nice job. By the way, can you write a script to create/update license information in files? Or use existing tools to do this.
> > 
> > 
> > 
> > Oh, I forgot to mention. So, there are [some existing tools](https://spdx.dev/tools-community/), and I personally choose to use [fsfe/reuse-tool](https://github.com/fsfe/reuse-tool). It's written in Python and can be installed by `pipx install reuse` (my preferred way). You can also use `pip` or `conda` to install it, or run it directly with `pipx run reuse ...`.
> > 
> > 
> > 
> > What I've done is:
> > 
> > 
> > 
> > ```bash
> > 
> > reuse annotate --license "GPL-3.0-or-later" \
> > 
> >                --copyright-style string-c \
> > 
> >                --year "2022-2023" \
> > 
> >                --copyright "PMR Fansub" \
> > 
> >                src/components/* src/config/* ... # specify files to annotate
> > 
> > ```
> > 
> > 
> 
> Consider adding the instructions to the document.

Will add this to the contribution guide.

**Comment by johanvx** [comment]
> SVG files are still not covered.

The license notice of SVG files and third-party projects will be added in a separate PR, but probably not in the near future.

**Comment by johanvx** [comment]
Draft now. Wait for the update of the contribution guide.

**Pull request merged**
